In [4]:
import pandas as pd

appointments = pd.read_csv("../data/appointments.csv")
patients = pd.read_csv("../data/patients.csv")
slots = pd.read_csv("../data/slots.csv")

In [ ]:
appointments.head() #show first 5 rows of appointments table

,appointment_id,slot_id,scheduling_date,appointment_date,appointment_time,scheduling_interval,status,check_in_time,appointment_duration,start_time,end_time,waiting_time,patient_id,sex,age,age_group
0,138,1,2014-12-28,2015-01-01,08:00:00,4,did not attend,NaN,NaN,NaN,NaN,NaN,8285,Male,37,35-39
1,146,23,2014-12-29,2015-01-01,13:30:00,3,did not attend,NaN,NaN,NaN,NaN,NaN,5972,Male,84,80-84
2,21,24,2014-12-17,2015-01-01,13:45:00,15,attended,13:36:45,5.2,13:37:57,13:43:09,1.2,6472,Male,77,75-79
3,233,25,2014-12-31,2015-01-01,14:00:00,1,attended,13:59:32,28.9,14:00:40,14:29:34,1.1,5376,Female,37,35-39
4,90,26,2014-12-26,2015-01-01,14:15:00,6,cancelled,NaN,NaN,NaN,NaN,NaN,8028,Male,72,70-74

In [ ]:
appointments.shape #checking size of dataset (# or rows, # of columns)

(111488, 16)

In [10]:
appointments.info() #gives more detailed info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111488 entries, 0 to 111487
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   appointment_id        111488 non-null  int64
 1   slot_id               111488 non-null  int64
 2   scheduling_date       111488 non-null  object
 3   appointment_date      111488 non-null  object
 4   appointment_time      111488 non-null  object
 5   scheduling_interval   111488 non-null  int64
 6   status                111488 non-null  object
 7   check_in_time         86032 non-null   object
 8   appointment_duration  86032 non-null   float64
 9   start_time            86032 non-null   object
 10  end_time              86032 non-null   object
 11  waiting_time          86032 non-null   float64
 12  patient_id            111488 non-null  int64
 13  sex                   111488 non-null  object
 14  age                   111488 non-null  int64
 15  age_group             111488 non-null  object
dtypes: float64(2), int64(5), object(9)
memory usage: 13.6+ MB

In [12]:
appointments["status"].value_counts() #how many appointments were atteneded,cancelled,noshows,etc.

status
attended          86032
cancelled         18254
did not attend     6615
unknown             446
scheduled           141
Name: count, dtype: int64

In [14]:
appointments.duplicated().sum() #checks for duplicated rows in appointments dataset
#.duplicated() checks if each row is a duplicate of the previous row and gives T/F
#.sum() counts the true values

np.int64(0)

In [16]:
appointments.isnull().sum() #counts missing values for each column

appointment_id              0
slot_id                     0
scheduling_date             0
appointment_date            0
appointment_time            0
scheduling_interval         0
status                      0
check_in_time           25456
appointment_duration    25456
start_time              25456
end_time                25456
waiting_time            25456
patient_id                  0
sex                         0
age                         0
age_group                   0
dtype: int64

In [18]:
#converts values into dates and saves it back into the same column
appointments["scheduling_date"] = pd.to_datetime(appointments["scheduling_date"])
appointments["appointment_date"] = pd.to_datetime(appointments["appointment_date"])

In [20]:
appointments[["scheduling_date", "appointment_date"]].dtypes

scheduling_date     datetime64[ns]
appointment_date    datetime64[ns]
dtype: object

In [22]:
appointments[["appointment_time", "check_in_time", "start_time", "end_time"]].head(10)

  appointment_time check_in_time start_time  end_time
0         08:00:00           NaN        NaN       NaN
1         13:30:00           NaN        NaN       NaN
2         13:45:00      13:36:45   13:37:57  13:43:09
3         14:00:00      13:59:32   14:00:40  14:29:34
4         14:15:00           NaN        NaN       NaN
5         14:30:00      14:08:53   14:30:38  14:38:20
6         14:45:00      14:22:59   14:39:14  14:43:26
7         15:00:00      14:59:06   15:00:08  15:27:14
8         15:15:00           NaN        NaN       NaN
9         13:15:00      13:05:52   13:14:25  13:15:37

In [24]:
#.describe() --> gives summary statistics for numerical columns + catch weird values
appointments[["scheduling_interval", "appointment_duration", "waiting_time", "age"]].describe()

       scheduling_interval  appointment_duration  waiting_time            age
count        111488.000000          86032.000000  86032.000000  111488.000000
mean              7.190146             17.479525     44.086509      57.205206
std               6.146793             11.064225     40.788791      20.158119
min               1.000000              0.000000      0.600000      15.000000
25%               2.000000              8.600000     12.600000      40.000000
50%               5.000000             15.800000     33.500000      59.000000
75%              10.000000             24.700000     64.600000      74.000000
max              30.000000             58.700000    297.300000     100.000000

In [26]:
#shows appointments where appointment duration was 0 minutes
appointments[appointments["appointment_duration"] == 0]

,appointment_id,slot_id,scheduling_date,appointment_date,appointment_time,scheduling_interval,status,check_in_time,appointment_duration,start_time,end_time,waiting_time,patient_id,sex,age,age_group
6466,6592,6027,2015-07-27,2015-07-30,14:30:00,3,attended,14:30:58,0.0,17:29:16,17:29:16,178.3,9356,Male,70,70-74
12233,12405,11383,2016-01-31,2016-02-03,13:30:00,3,attended,13:07:58,0.0,13:38:17,13:38:17,30.3,9088,Male,16,15-19
18935,18909,17575,2016-08-31,2016-09-07,11:30:00,7,attended,11:11:30,0.0,11:19:58,11:19:58,8.5,5741,Male,78,75-79
19856,19991,18464,2016-10-05,2016-10-07,13:45:00,2,attended,13:34:25,0.0,13:35:31,13:35:31,1.1,4043,Female,84,80-84
20958,21095,19457,2016-11-10,2016-11-11,12:00:00,1,attended,11:44:32,0.0,12:13:41,12:13:41,29.2,121,Female,21,20-24
35257,35439,32784,2018-02-19,2018-02-21,13:45:00,2,attended,13:17:56,0.0,13:18:54,13:18:54,1.0,2831,Female,90,90+
39284,39324,36552,2018-06-26,2018-07-03,15:45:00,7,attended,15:32:13,0.0,15:32:58,15:32:58,0.8,18077,Male,76,75-79
50264,50347,46800,2019-06-22,2019-06-26,17:45:00,4,attended,17:47:46,0.0,18:28:51,18:28:51,41.1,15882,Female,30,30-34
53129,53183,49409,2019-09-21,2019-09-26,10:00:00,5,attended,09:54:45,0.0,10:28:42,10:28:42,34.0,11063,Female,74,70-74
55159,55240,51291,2019-11-27,2019-12-02,10:30:00,5,attended,10:30:19,0.0,10:31:10,10:31:10,0.9,20182,Female,26,25-29
66255,66442,61663,2020-11-26,2020-11-27,13:30:00,1,attended,13:08:14,0.0,13:57:29,13:57:29,49.3,21787,Female,55,55-59
85636,85870,79709,2022-08-21,2022-08-22,15:00:00,1,attended,14:52:34,0.0,14:55:47,14:55:47,3.2,28680,Female,81,80-84
89938,89954,83688,2023-01-02,2023-01-09,09:45:00,7,attended,09:21:53,0.0,09:55:57,09:55:57,34.1,14579,Male,79,75-79
92097,91900,85683,2023-03-06,2023-03-20,08:30:00,14,attended,08:30:33,0.0,08:46:05,08:46:05,15.5,232,Female,51,50-54
92595,92739,86187,2023-04-02,2023-04-05,14:30:00,3,attended,14:35:30,0.0,15:28:15,15:28:15,52.7,6329,Male,43,40-44
93476,93603,86970,2023-04-30,2023-05-03,10:15:00,3,attended,09:50:06,0.0,09:51:05,09:51:05,1.0,29259,Female,76,75-79
97940,97588,91156,2023-09-06,2023-09-26,16:45:00,20,attended,16:22:17,0.0,16:35:02,16:35:02,12.8,25096,Female,68,65-69
103795,103480,96540,2024-03-16,2024-04-02,12:45:00,17,attended,12:35:18,0.0,13:00:55,13:00:55,25.6,20737,Male,25,25-29

In [28]:
#creates new column called appointment_day and saves weekday names into it
appointments["appointment_day"] = appointments["appointment_date"].dt.day_name()

In [30]:
appointments[["appointment_date", "appointment_day"]].head()

  appointment_date appointment_day
0       2015-01-01        Thursday
1       2015-01-01        Thursday
2       2015-01-01        Thursday
3       2015-01-01        Thursday
4       2015-01-01        Thursday

In [32]:
#extracting the hour
appointments["appointment_hour"] = pd.to_datetime(
    appointments["appointment_time"],
    format="%H:%M:%S"
).dt.hour

In [34]:
appointments[["appointment_time", "appointment_hour"]].head()

  appointment_time  appointment_hour
0         08:00:00                 8
1         13:30:00                13
2         13:45:00                13
3         14:00:00                14
4         14:15:00                14

In [ ]:
#categorize appointment times to create morning, afternoon, and evening
def get_time_period(hour):
    if hour < 12:
        return "Morning"
    elif hour < 17:
        return "Afternoon"
    else:
        return "Evening"

In [37]:
#applying the function to the whole appoint_hour column
appointments["time_period"] = appointments["appointment_hour"].apply(get_time_period)

In [39]:
appointments[["appointment_time", "appointment_hour", "time_period"]].head(10)

  appointment_time  appointment_hour time_period
0         08:00:00                 8     Morning
1         13:30:00                13   Afternoon
2         13:45:00                13   Afternoon
3         14:00:00                14   Afternoon
4         14:15:00                14   Afternoon
5         14:30:00                14   Afternoon
6         14:45:00                14   Afternoon
7         15:00:00                15   Afternoon
8         15:15:00                15   Afternoon
9         13:15:00                13   Afternoon

In [41]:
appointments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111488 entries, 0 to 111487
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   appointment_id        111488 non-null  int64
 1   slot_id               111488 non-null  int64
 2   scheduling_date       111488 non-null  datetime64[ns]
 3   appointment_date      111488 non-null  datetime64[ns]
 4   appointment_time      111488 non-null  object
 5   scheduling_interval   111488 non-null  int64
 6   status                111488 non-null  object
 7   check_in_time         86032 non-null   object
 8   appointment_duration  86032 non-null   float64
 9   start_time            86032 non-null   object
 10  end_time              86032 non-null   object
 11  waiting_time          86032 non-null   float64
 12  patient_id            111488 non-null  int64
 13  sex                   111488 non-null  object
 14  age                   111488 non-null  int64
 15  age_group             111488 non-null  object
 16  appointment_day       111488 non-null  object
 17  appointment_hour      111488 non-null  int32
 18  time_period           111488 non-null  object
dtypes: datetime64[ns](2), float64(2), int32(1), int64(5), object(9)
memory usage: 15.7+ MB

In [42]:
#saving the cleaned version
appointments.to_csv("../data/appointments_cleaned.csv", index=False)